<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Capa_de_Datos</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Entities\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="Repositories\Implementations\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
